### ISSUE TITLE
failed to build again in webpack process.

### ISSUE THREAD

**Issue by bjmin** [postcss/postcss-import#118]
I use postcss-import in webpack, but it will be failed once compile an error file, though I'm not very sure the ERROR is caused by postcss-import.

here is the log:
```
ERROR in ./~/css-loader!./~/postcss-loader!./example/app.css
postcss-import: /Users/bjmin/Documents/repo/github/iconist/master/example/style/header.css:10:52: Missed semicolon
  color: $white;
  text-shadow: .025em .025em 0 $red, .05em .05em 0 $kal
                                                   ^
ERROR in ./~/css-loader!./~/postcss-loader!./example/app.css
Module build failed: TypeError: Cannot read property 'toString' of undefined
  at new Input (/Users/bjmin/Documents/repo/github/iconist/master/node_modules/postcss/lib/input.js:31:23)
  at parse (/Users/bjmin/Documents/repo/github/iconist/master/node_modules/postcss/lib/parse.js:22:17)
  at new LazyResult (/Users/bjmin/Documents/repo/github/iconist/master/node_modules/postcss/lib/lazy-result.js:61:24)
  at Processor.process (/Users/bjmin/Documents/repo/github/iconist/master/node_modules/postcss/lib/processor.js:38:16)
  at processCss (/Users/bjmin/Documents/repo/github/iconist/master/node_modules/css-loader/lib/processCss.js:171:11)
  at Object.module.exports (/Users/bjmin/Documents/repo/github/iconist/master/node_modules/css-loader/lib/loader.js:24:2)
 @ ./example/app.css 4:14-116 13:2-17:4 14:20-122
```

caused by this line:
```
@import './colors.css';

header {

  height: 300px;
  width: 100%;

  background: $red;
  color: $white;
  text-shadow: .025em .025em 0 $red, .05em .05em 0 $kal <<<<<<<

  font-size: 8em;

  cursor: default;
  user-select: none;

}
```

but after fix it, the webpack won't compile agian until I trigger save event in main file which import the error partial file.

here is my webpack config:
```coffeescript
  postcss: (bundler) ->

    plugins = [
      postcssImport addDependencyTo: bundler
      postcssNested
      postcssSimpleVars
      postcssUrl
      autoprefixer AUTOPREFIXER_OPTIONS
    ]

    if PROD
      plugins = plugins.concat [
        cssnano CSSNANO_OPTIONS
      ]

    plugins
```

**Comment by MoOx** [comment]
The error is pretty clear

> postcss-import: /Users/bjmin/Documents/repo/github/iconist/master/example/style/header.css:10:52: Missed semicolon

**Missed semicolon**.

**Comment by bjmin** [comment]
But once i fixed the error, webpack won't compile agian. is that some cache problem?

**Comment by MoOx** [comment]
https://github.com/postcss/postcss-loader#integration-with-postcss-import

**Comment by bjmin** [comment]
I cannot find any mistake on my config... but thx~

**Comment by MoOx** [comment]
What is your config?
