### ISSUE TITLE
TypeError from Empty Files or Directories

### ISSUE THREAD

**Issue by msfragala** [postcss/postcss-import#155]
I'm getting an error like so when there's an empty file or directory in the import glob. I'm using the the latest version (7.1.3) to date.
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'before' of undefined
    at Stringifier.raw (/Users/Mitchell/Documents/Repository/jm-lofts/node_modules/postcss/lib/stringifier.js:119:30)
    at Stringifier.body (/Users/Mitchell/Documents/Repository/jm-lofts/node_modules/postcss/lib/stringifier.js:91:31)
    at Stringifier.block (/Users/Mitchell/Documents/Repository/jm-lofts/node_modules/postcss/lib/stringifier.js:103:18)
    at Stringifier.rule (/Users/Mitchell/Documents/Repository/jm-lofts/node_modules/postcss/lib/stringifier.js:60:14)
    at Stringifier.stringify (/Users/Mitchell/Documents/Repository/jm-lofts/node_modules/postcss/lib/stringifier.js:33:24)
    at Stringifier.body (/Users/Mitchell/Documents/Repository/jm-lofts/node_modules/postcss/lib/stringifier.js:93:18)
    at Stringifier.root (/Users/Mitchell/Documents/Repository/jm-lofts/node_modules/postcss/lib/stringifier.js:37:14)
    at Stringifier.stringify (/Users/Mitchell/Documents/Repository/jm-lofts/node_modules/postcss/lib/stringifier.js:33:24)
    at _class.stringify (/Users/Mitchell/Documents/Repository/jm-lofts/node_modules/postcss/lib/stringify.js:14:9)
    at _class.generate (/Users/Mitchell/Documents/Repository/jm-lofts/node_modules/postcss/lib/map-generator.js:278:18)
```

**Comment by TrySound** [comment]
@msfragala We will remove glob support in 8.0 but I'll create a wrapper version with a few sassy features. For now we can't make patch for old stuff.

**Comment by msfragala** [comment]
Oh, I see. I guess I'll need to create plugin of my own if I want this functionality then. How come you guys are dropping support for globbing, if I might ask?

**Comment by TrySound** [comment]
@msfragala I will make wrapper for features in the same time with import 8 release.

**Comment by MoOx** [comment]
@TrySound Any ETA?

**Comment by MoOx** [comment]
Relevant in 8.x?

**Comment by TrySound** [comment]
Think so
