### ISSUE TITLE
postcss v8.0.0 cant find module  './lib/join-media'

### ISSUE THREAD

**Issue by Havunen** [postcss/postcss-import#161]
Just installed postcss-import v8.0.0 and it failed with exception:

```
Error: Cannot find module './lib/join-media'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\GIT\SeveraUI\node_modules\postcss-import\index.js:4:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

Looks like ./lib folders are not included in package installed from npm. 
```javascript
  "files": [
    "index.js"
  ],
```

missing lib folder?

Havunen

**Comment by TrySound** [comment]
@MoOx Need to add "lib"

**Comment by MoOx** [comment]
On it.

**Comment by TrySound** [comment]
Add me on npm just in case

**Comment by MoOx** [comment]
What's your nick?

**Comment by TrySound** [comment]
trysound

**Comment by MoOx** [comment]
Added.

**Comment by MoOx** [comment]
8.0.1 released.

**Comment by MoOx** [comment]
"npm run release" :)
