### ISSUE TITLE
postcss-import 8.1.2 won't work when used with postcss 5.1

### ISSUE THREAD

**Issue by madx** [postcss/postcss-import#223]
When using `postcss-import` 8.1.2 with `postcss` 5.1 (through cssnext) I get the following error:

```
ERROR in ./src/styles.css
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'length' of undefined
    at module.exports (/home/madx/[redacted]/node_modules/postcss-import/lib/join-media.js:6:40)
    at /home/madx/[redacted]/node_modules/postcss-import/index.js:167:18
    at Array.map (native)
    at parseStyles (/home/madx/[redacted]/node_modules/postcss-import/index.js:166:33)
    at /home/madx/[redacted]/node_modules/postcss-import/index.js:48:12
    at LazyResult.run (/home/madx/[redacted]/node_modules/postcss/lib/lazy-result.js:286:20)
    at /home/madx/[redacted]/node_modules/postcss/lib/lazy-result.js:200:37
    at LazyResult.asyncTick (/home/madx/[redacted]/node_modules/postcss/lib/lazy-result.js:214:15)
    at processing.Promise.then._this2.processed (/home/madx/[redacted]/node_modules/postcss/lib/lazy-result.js:240:20)
    at LazyResult.async (/home/madx/[redacted]/node_modules/postcss/lib/lazy-result.js:237:27)
    at LazyResult.then (/home/madx/[redacted]/node_modules/postcss/lib/lazy-result.js:141:21)
    at Object.module.exports (/home/madx/[redacted]/node_modules/postcss-loader/index.js:63:10)
    at DependenciesBlock.onModuleBuildFailed (/home/madx/[redacted]/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/home/madx/[redacted]/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /home/madx/[redacted]/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/home/madx/[redacted]/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at /home/madx/[redacted]/node_modules/postcss-loader/index.js:74:17
    at runMicrotasksCallback (internal/process/next_tick.js:58:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./src/index.js 27:0-23
```

I suspect the bug to be linked to breaking changes in postcss since it was working with previous version :)

**Comment by jedmao** [comment]
I'm also trying to figure out a fix for this issue.

**Comment by nixegend** [comment]
+1
```
ERROR in ./~/css-loader?camelCase&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./src/modules/top-bar/styles/top-bar.css
Module build failed: TypeError: Cannot read property 'length' of undefined
    at module.exports (D:\DW-WEB\node_modules\postcss-import\lib\join-media.js:2:40)
    at D:\DW-WEB\node_modules\postcss-import\index.js:167:18
    at Array.map (native)
    at parseStyles (D:\DW-WEB\node_modules\postcss-import\index.js:166:33)
    at D:\DW-WEB\node_modules\postcss-import\index.js:48:12
    at LazyResult.run (D:\DW-WEB\node_modules\postcss\lib\lazy-result.js:286:20)
    at D:\DW-WEB\node_modules\postcss\lib\lazy-result.js:200:37
    at LazyResult.asyncTick (D:\DW-WEB\node_modules\postcss\lib\lazy-result.js:214:15)
    at processing.Promise.then._this2.processed (D:\DW-WEB\node_modules\postcss\lib\lazy-result.js:240:20)
    at LazyResult.async (D:\DW-WEB\node_modules\postcss\lib\lazy-result.js:237:27)
    at LazyResult.then (D:\DW-WEB\node_modules\postcss\lib\lazy-result.js:141:21)
    at Object.module.exports (D:\DW-WEB\node_modules\postcss-loader\index.js:63:10)
 @ ./src/modules/top-bar/styles/top-bar.css 4:14-221 13:2-17:4 14:20-227
webpack: bundle is now VALID.
```

**Comment by Dangoo** [comment]
Same here, when running via JS-API it fails silently and running with `postcss-cli`I get the same error log as @nixegend 

So +1

**Comment by NicolasGraph** [comment]
+1 `[TypeError: Cannot read property 'length' of undefined]`

**Comment by MoOx** [comment]
If this is a postcss issue, did some opened an issue on  postcss  repo?

Btw #210...

**Comment by MoOx** [comment]
poke @ai Are you aware of this regression?

**Comment by 1j01** [comment]
I tried to patch [join-media.js](https://github.com/postcss/postcss-import/blob/91bd131015fcfc4ab8903fb85fdb34a01286fd2f/lib/join-media.js#L2-L10) with this:
```js
  if (!(parentMedia && parentMedia.length) && (childMedia && childMedia.length)) {
    return childMedia
  }
  if ((parentMedia && parentMedia.length) && !(childMedia && childMedia.length)) {
    return parentMedia
  }
  if (!(parentMedia && parentMedia.length) && !(childMedia && childMedia.length)) {
    return []
  }
```
but it just got rid of the `@import`s without replacing them with content.

Worked around this and/or #227 by downgrading to v7. `npm i postcss-import@7 --save-dev`

**Comment by cmnstmntmn** [comment]
i'm having same issue. downgrading to `v7` fixed the issue

**Comment by RyanZim** [comment]
I would like to investigate this, however, I am not a webpack expert. Can somebody make a reduced-test-case repo demonstrating this issue?

**Comment by RyanZim** [comment]
Does anyone still have this issue with the latest versions?

If I don't hear anything within a few days, I will close.

**Comment by Dangoo** [comment]
Just made a little testcase with
- postcss
- postcss-cli
- postcss-import

**foo.css**
```css
body {
    color: red;
}
```

**index.css**
```css
@import 'foo';

.bar {
    color: green;
}
```

**config.json**
```json
{
    "use": ["postcss-import"],
    "input": "index.css",
    "output": "bundle.css"
}
```

```
$ postcss -c config.json
```

And the output was as aspected:
**bundle.css**
```css
body {
    color: red;
}

.bar {
    color: green;
}
```

=> Seems solved for me. Even chained imports work well.

**Comment by RyanZim** [comment]
@Dangoo Thanks! I'll leave this open for a few more days to make sure no one else has this problem.

**Comment by RyanZim** [comment]
Alright, I guess this is fixed, closing. If anyone else has this problem with the latest version, please open an new issue.
