### ISSUE TITLE
Error when try to import css file with inline URLs()

### ISSUE THREAD

**Issue by schel4ok** [postcss/postcss-import#450]
In my app.css I have string `@import 'lightgallery.js';` which should import styles for lightgallery plugin from node_modules.
But after `npm run dev` I got errors that  relative modules were not found.

```
npm run dev

> dev
> npm run development


> development
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js

98% after emitting SizeLimitsPlugin

 ERROR  Failed to compile with 7 errors                               9:06:04 PM

These relative modules were not found:

* ../fonts/lg.svg?22t19m in ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css
* ../fonts/lg.ttf?22t19m in ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css
* ../fonts/lg.woff?22t19m in ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css
* ../img/loading.gif in ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css
* ../img/video-play.png in ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css
* ../img/vimeo-play.png in ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css
* ../img/youtube-play.png in ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css
     Asset     Size   Chunks             Chunk Names
/js/app.js  730 KiB  /js/app  [emitted]  /js/app

ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/css-loader/index.js):
ModuleNotFoundError: Module not found: Error: Can't resolve '../fonts/lg.svg?22t19m' in '/home/http/app/resources/css'
    at /home/http/app/node_modules/webpack/lib/Compilation.js:925:10
    at /home/http/app/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /home/http/app/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/http/app/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/http/app/node_modules/neo-async/async.js:2830:7
    at /home/http/app/node_modules/neo-async/async.js:6877:13
    at /home/http/app/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /home/http/app/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /home/http/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/http/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/http/app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/http/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/http/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/http/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/http/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/http/app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/http/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/http/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/http/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/http/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/http/app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/http/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/http/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/http/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/http/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/http/app/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15
    at /home/http/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (node:internal/process/task_queues:75:11)
 @ ./resources/css/app.css

ERROR in ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css)
Module not found: Error: Can't resolve '../fonts/lg.svg?22t19m' in '/home/http/app/resources/css'
 @ ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css) 7:1351805-1351838
 @ ./resources/css/app.css

ERROR in ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css)
Module not found: Error: Can't resolve '../fonts/lg.ttf?22t19m' in '/home/http/app/resources/css'
 @ ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css) 7:1351654-1351687
 @ ./resources/css/app.css

ERROR in ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css)
Module not found: Error: Can't resolve '../fonts/lg.woff?22t19m' in '/home/http/app/resources/css'
 @ ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css) 7:1351731-1351765
 @ ./resources/css/app.css

ERROR in ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css)
Module not found: Error: Can't resolve '../img/loading.gif' in '/home/http/app/resources/css'
 @ ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css) 7:1368504-1368533
 @ ./resources/css/app.css

ERROR in ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css)
Module not found: Error: Can't resolve '../img/video-play.png' in '/home/http/app/resources/css'
 @ ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css) 7:1359119-1359151
 @ ./resources/css/app.css

ERROR in ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css)
Module not found: Error: Can't resolve '../img/vimeo-play.png' in '/home/http/app/resources/css'
 @ ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css) 7:1358797-1358829 7:1358953-1358985
 @ ./resources/css/app.css

ERROR in ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css)
Module not found: Error: Can't resolve '../img/youtube-play.png' in '/home/http/app/resources/css'
 @ ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css) 7:1359422-1359456 7:1359582-1359616
 @ ./resources/css/app.css

```

Here is my webpack
```
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
   .scripts([
    	  'public/js/app.js',
    	  'resources/js/includes/script.js'
	  ],  'public/js/app.js')
   .postCss('resources/css/app.css', 'public/css', [
      require('postcss-import'), 
      require('tailwindcss'),
      require('postcss-extend'), 
      require('postcss-nested'),
      require('autoprefixer'),
    ]);
```

in resources/css/app.css I have string `@import 'lightgallery.js';` which gives me this error.
Lightgallery.js should be imported from `\node_modules\lightgallery.js\dist\css\lightgallery.css`

Inside `lightgallery.css` there are urls like that
```
src: url("../fonts/lg.ttf?22t19m") format("truetype"), url("../fonts/lg.woff?22t19m") format("woff"), url("../fonts/lg.svg?22t19m#lg") format("svg");
background: url("../img/vimeo-play.png") no-repeat scroll 0 -58px transparent;
```

**Comment by RyanZim** [comment]
Your error is coming from webpack, when it tries to inline those relative URLs. Those URLs of course assume that the file is in `node_modules`, then postcss-import is inlining the CSS, and webpack is looking relative to your input file. You'll need to either tweak your webpack config, or use https://github.com/postcss/postcss-url to rebase your URLs.

**Comment by schel4ok** [comment]
postcss-url doesn't help in this case. Error is the same.
I think that the problem is because postcss-import copies css file, but doesn't copy fonts and images from node_modules to public folder

**Comment by RyanZim** [comment]
> I think that the problem is because postcss-import copies css file, but doesn't copy fonts and images from node_modules to public folder

Right, that's the problem. So you need to use postcss-url to rebase the URLs to point to node_modules so webpack can handle bundling the assets.
