### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'before' of undefined

### ISSUE THREAD

**Issue by brandondurham** [postcss/postcss-import#78]
I'm using postcss in a Webpack project using the postcss-loader. I'm looking to store my global vars in a single `index.css` file and pull that in where needed. As soon as I add the `postcss-import` plugin and an import statement I get the following error:

```
ERROR in ./~/css-loader?modules&localIdentName=[name]--[local]_[hash:base64:5]!./~/postcss-loader!./src/js/website.com/components/Button/Button.css
Module build failed: TypeError: Cannot read property 'before' of undefined
    at Stringifier.raw (/Users/username/Sites/website/node_modules/postcss-loader/node_modules/postcss/lib/stringifier.js:121:30)
    at Stringifier.body (/Users/username/Sites/website/node_modules/postcss-loader/node_modules/postcss/lib/stringifier.js:93:31)
    at Stringifier.root (/Users/username/Sites/website/node_modules/postcss-loader/node_modules/postcss/lib/stringifier.js:37:14)
    at Stringifier.stringify (/Users/username/Sites/website/node_modules/postcss-loader/node_modules/postcss/lib/stringifier.js:33:24)
    at _default.stringify (/Users/username/Sites/website/node_modules/postcss-loader/node_modules/postcss/lib/stringify.js:14:9)
    at _default.generateString (/Users/username/Sites/website/node_modules/postcss-loader/node_modules/postcss/lib/map-generator.js:231:14)
    at _default.generateMap (/Users/username/Sites/website/node_modules/postcss-loader/node_modules/postcss/lib/map-generator.js:189:14)
    at _default.generate (/Users/username/Sites/website/node_modules/postcss-loader/node_modules/postcss/lib/map-generator.js:271:25)
    at LazyResult.stringify (/Users/username/Sites/website/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:221:24)
    at /Users/username/Sites/website/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:158:27
    at lib$es6$promise$$internal$$tryCatch (/Users/username/Sites/website/node_modules/autoprefixer-core/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:331:16)
    at lib$es6$promise$$internal$$invokeCallback (/Users/username/Sites/website/node_modules/autoprefixer-core/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:343:17)
    at /Users/username/Sites/website/node_modules/autoprefixer-core/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:891:13
    at Object.lib$es6$promise$asap$$flush [as _onImmediate] (/Users/username/Sites/website/node_modules/autoprefixer-core/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:125:9)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
 @ ./src/js/website.com/components/Button/Button.css 4:14-198
```

This is my loader:

```
{
	test: /\.(css)$/,
	loader: 'style-loader!css-loader?modules&localIdentName=[name]--[local]_[hash:base64:5]!postcss-loader'
}
```

… and the postcss config:

```
postcss: function () {
	return [
		require('postcss-import'),
		require('postcss-custom-properties'),
		require('postcss-mixins')
	];
}
```

Any ideas?

**Comment by ai** [comment]
It is because this PR still not accepted https://github.com/postcss/postcss-import/pull/76

**Comment by brandondurham** [comment]
Ahh, damn. Thanks for the super quick response. I'll upgrade locally until it's approved.

**Comment by MoOx** [comment]
Dup of #75

**Comment by MoOx** [comment]
@ai you can see that the postcssVersion thing is not helping here :/

**Comment by cbrwizard** [comment]
I am also getting this error now, using latest version (I guess)

**Comment by MoOx** [comment]
Please provide full trace of the error and your exact postcss and plugin versions.
